stages:
  - deploy

deploy-ansible:
  stage: deploy
  image: unicred/ansible-docker
  variables:
    GITLAB_RUNNER_REPLICAS: 3
    GITLAB_URL: "https://gitlab-lab.docs-planet.site/"
    ANSIBLE_LIMIT: all
  before_script:
    - echo "Setting environment"
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d ' ' | base64 --decode | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Deploying via ansible"
    - >
      cd ansible && ansible-playbook main.yaml -i inventory \
       -e gitlab_registration_token=${GITLAB_REGISTRATION_TOKEN} \
       -e gitlab_runner_replicas=${GITLAB_RUNNER_REPLICAS} \
       -e deploy_runner="${DEPLOY_RUNNER}" \
       -e delete_runner="${DELETE_RUNNER}" \
       --limit=${ANSIBLE_LIMIT}
  tags:
    - deploy
  when: manual
  except:
    variables:
      - $SKIP_DEPLOY
